# Generated by Django 2.0.4 on 2018-05-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter your specific comments here', max_length=1000)),
                ('start_time', models.DateTimeField(verbose_name='Starting time of the appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter grooming option here', max_length=200)),
                ('price', models.FloatField(verbose_name='Price to be charged')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('home_phone', models.IntegerField(help_text='Enter your phone without preceding zeros.')),
                ('work_phone', models.IntegerField(help_text='Enter your phone without preceding zeros.')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggroomer.User'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggroomer.Dog'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='option',
            field=models.ManyToManyField(help_text='Select options for this appointment', to='doggroomer.Option'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggroomer.User'),
        ),
    ]
