# Generated by Django 2.0.4 on 2018-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggroomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='hassan', max_length=50),
            preserve_default=False,
        ),
    ]
